export const BARANGAYS: readonly string[] = [
    "Assumption",
    "Bagong Buhay",
    "Bagong Buhay II",
    "Bagong Buhay III",
    "Citrus",
    "Ciudad Real",
    "Dulong Bayan",
    "Fatima",
    "Fatima II",
    "Fatima III",
    "Fatima IV",
    "Fatima V",
    "Francisco Homes-Guijo",
    "Francisco Homes-Mulawin",
    "Francisco Homes-Narra",
    "Francisco Homes-Yakal",
    "Gaya-gaya",
    "Graceville",
    "Gumaoc Central",
    "Gumaoc East",
    "Gumaoc West",
    "Kaybanban",
    "Kaypian",
    "Lawang Pari",
    "Maharlika",
    "Minuyan",
    "Minuyan II",
    "Minuyan III",
    "Minuyan IV",
    "Minuyan Proper",
    "Minuyan V",
    "Muzon",
    "Paradise III",
    "Poblacion",
    "Poblacion I",
    "San Isidro",
    "San Manuel",
    "San Martin",
    "San Martin II",
    "San Martin III",
    "San Martin IV",
    "San Pedro",
    "San Rafael",
    "San Rafael I",
    "San Rafael III",
    "San Rafael IV",
    "San Rafael V",
    "San Roque",
    "Santa Cruz",
    "Santa Cruz II",
    "Santa Cruz III",
    "Santa Cruz IV",
    "Santa Cruz V",
    "Santo Cristo",
    "Santo Niño",
    "Santo Niño II",
    "Sapang Palay",
    "St. Martin de Porres",
    "Tungkong Mangga",
] as const;
